services:
  postgres:
    image: "docker.io/library/postgres:17"
    ports:
     - "5432:5432/tcp"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: radio
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  rabbitmq:
    hostname: rabbitmq-radio
    image: "docker.io/library/rabbitmq:4.2.4-management-alpine"
    ports:
      - "5672:5672/tcp"
      - "15672:15672/tcp"
    environment:
      RABBITMQ_DEFAULT_USER: radio
      RABBITMQ_DEFAULT_PASS: radio
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
      - ./rabbitmq/log:/var/log/rabbitmq
  ome:
    image: "docker.io/airensoft/ovenmediaengine:v0.20.0"
    ports:
      - "8081:8081/tcp" # API
      - "9999:9999/udp" # SRT ingest
      - "9998:9998/udp" # SRT publishing
      - "3333:3333/tcp" # HLS
    volumes:
      - "./conf/OME_Server.dev.xml:/opt/ovenmediaengine/bin/origin_conf/Server.xml:ro"
      - "./conf/OME_Record.dev.xml:/opt/ovenmediaengine/bin/origin_conf/Record.xml:ro"
      - "./conf/OME_Vhost.dev.xml:/opt/ovenmediaengine/bin/origin_conf/vhosts/dev.xml:ro"
      - "./ome_log:/var/log/ovenmediaengine"
      - "./recordings:/recordings"
