[package]
name = "stream-controller"
version = "0.2.0"
edition = "2024"

[dependencies]
axum = "0.8.8"
miette = { version = "7.6.0", features = ["fancy"] }
regex = "1.12.3"
serde = "1.0.228"
systemd-zbus = "5.3.2" # dead library?
tokio = { version = "1.51.0", features = ["full"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
zbus = { version = "5.14.0", features = ["tokio"] }
