# Generated by Django 6.0.2 on 2026-02-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livestreams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="livestream",
            name="status",
            field=models.CharField(
                choices=[("P", "Pending"), ("L", "Live"), ("E", "Ended")],
                default="P",
                max_length=1,
            ),
        ),
    ]
