# Generated by Django 6.0.2 on 2026-02-27 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livestreams", "0002_livestream_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="LivestreamTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField()),
                (
                    "livestream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="livestreams.livestream",
                    ),
                ),
            ],
            options={
                "unique_together": {("livestream", "tag")},
            },
        ),
    ]
