# Generated by Django 6.0.3 on 2026-04-11 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livestreams", "0003_livestreamtag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="livestream",
            name="status",
        ),
        migrations.AddField(
            model_name="livestream",
            name="ended_at",
            field=models.DateTimeField(
                default=None, null=True, verbose_name="stream ended at"
            ),
        ),
        migrations.AddField(
            model_name="livestream",
            name="started_at",
            field=models.DateTimeField(
                default=None, null=True, verbose_name="stream started at"
            ),
        ),
    ]
