# Generated by Django 6.0.3 on 2026-04-16 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livestreams", "0004_remove_livestream_status_livestream_ended_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngestPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                ("icecast_url", models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name="livestream",
            name="ingest_point",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="livestreams.ingestpoint",
            ),
        ),
    ]
