# Generated by Django 6.0.2 on 2026-03-10 13:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catchup", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="publish_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="publish at"
            ),
        ),
        migrations.AlterField(
            model_name="episode",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="uploaded at"),
        ),
    ]
