# Generated by Django 6.0.2 on 2026-03-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catchup", "0002_episode_publish_at_alter_episode_uploaded_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="original_file",
            field=models.FileField(
                default=None, null=True, upload_to="episodes/%Y/%m/%d/originals/"
            ),
        ),
    ]
