# Generated by Django 6.0.2 on 2026-03-26 22:12

import catchup.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catchup", "0003_episode_original_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="duration_secs",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="episode",
            name="processed_file",
            field=models.FileField(
                default=None, null=True, upload_to="episodes/%Y/%m/%d/processed/"
            ),
        ),
        migrations.AlterField(
            model_name="episode",
            name="original_file",
            field=models.FileField(
                default=None,
                null=True,
                upload_to="episodes/%Y/%m/%d/originals/",
                validators=[catchup.validators.validate_is_audio],
            ),
        ),
    ]
