on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8
      - name: Install python dependencies
        run: uv sync --color always --locked
      - name: Lint and check code style
        run: uv run ruff check
      - name: Run mypy type checking
        run: uv run mypy .
      - name: Start development services
        run: docker compose up -d
      - name: Run Django tests
        run: uv run manage.py test
